### ISSUE TITLE
Update button variants to match new variants in bitstyles update

### ISSUE THREAD

**Issue by ArinzeJeffrey-droid** [bitcrowd/bitstyles_phoenix#107]
- Add stories for each new variants (shape, color, size etc....)
- Check new buttons variant with the old ones to see if the classname matches the new visual representation of the new buttons
   check `lib/bitstyles_phoenix/bitstyles.ex` for examples.

**Comment by angelikatyborska** [comment]
Done in https://github.com/bitcrowd/bitstyles_phoenix/issues/122
