### ISSUE TITLE
id attribute should not be set on `label`

### ISSUE THREAD

**Issue by maltoe** [bitcrowd/bitstyles_phoenix#32]
For some reason I need to have my input field a custom `id` field, so I'm doing

```
ui_input f, :foo, id: "#custom"
```

This `id` is applied to both the `<input>` and the `<label>`

**Comment by andreasknoepfle** [comment]
This should be fixed already with #30 (see changelog). Options for labels are not forwarded anymore, but passed in explicitly via `label_opts`. 

We can close this with our next release.

**Comment by andreasknoepfle** [comment]
Fixed and released.
