### ISSUE TITLE
Support for LiveView

### ISSUE THREAD

**Issue by maltoe** [bitcrowd/bitstyles_phoenix#35]
Hello :wave:

What's the plan for LiveView support? :)

In particular, I'd like to be able to use `live_redirect` and `live_patch` in the `ui_button` helper. Any chance that will be supported soon? 💚 

🐱

**Comment by andreasknoepfle** [comment]
Hello 👋 

the next few things that were planned were other components like navbars and such, and an abstraction to use things like `alpine_js` to support drop down menus & navigation menus (and maybe tabs? etc). 

Is there anything else that we need to change apart from `ui_button`? 

Maybe we can get away with a `ui_button` version that can change the underlying function:
`ui_button("content", button_fn: &live_patch/2)`

PRs welcome 🥇
